name: Preprocessing Otomatis

on:
  push:
    paths:
      - '**/automate_*.py'
      - 'obesity_data_raw.csv'

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install pandas numpy scikit-learn

    - name: Jalankan script preprocessing
      run: |
        python preprocessing/automate_Bagus-Angkasawan-Sumantri-Putra.py

    - name: Tampilkan hasil output
      run: cat preprocessing/obesity_data_preprocessing.csv
      
    - name: Konfigurasi Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
    - name: Commit hasil preprocessing
      run: |
        git add preprocessing/obesity_data_preprocessing.csv
        git commit -m "Menambahkan hasil preprocessing otomatis [skip ci]" || echo "Tidak ada perubahan untuk di-commit"
        
    - name: Upload hasil preprocessing sebagai artifact
      uses: actions/upload-artifact@v2
      with:
        name: hasil-preprocessing
        path: preprocessing/obesity_data_preprocessing.csv
        retention-days: 90