name: Preprocessing Otomatis

on:
  push:
    paths:
      - '**/automate_*.py'
      - 'obesity_data_raw.csv'

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install pandas numpy scikit-learn

    - name: Jalankan script preprocessing
      run: python preprocessing/automate_Bagus-Angkasawan-Sumantri-Putra.py

    - name: Commit dan Push file hasil
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add preprocessing/obesity_data_preprocessing.csv
        git commit -m "Update hasil preprocessing otomatis"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
